ALTER TABLE clientes_neptuno
MODIFY IDCliente VARCHAR(5) PRIMARY KEY,
MODIFY NombreCompania VARCHAR(100) NOT NULL,
MODIFY Pais VARCHAR(15) NOT NULL,

ALTER TABLE CLIENTES RENAME Contactos;

ALTER TABLE Clientes
MODIFY Cod_Cliente VARCHAR(7) PRIMARY KEY,
MODIFY Empresa VARCHAR(100) NOT NULL,
MODIFY Ciudad VARCHAR(25) NOT NULL,
MODIFY Telefono INT NOT NULL,
MODIFY Responsable VARCHAR(30);

ALTER TABLE Pedidos
MODIFY Codigo_Cliente VARCHAR(7) NOT NULL,
MODIFY Fecha_Pedido DATE NOT NULL,
MODIFY Forma_Pago ENUM('APLAZADO', 'CONTADO', 'TARJETA'),
MODIFY Enviado ENUM('SI', 'NO');

ALTER TABLE Productos
MODIFY Cod_Producto INT PRIMARY KEY,
MODIFY Seccion VARCHAR(20) NOT NULL,
MODIFY Nombre VARCHAR(40) NOT NULL,
MODIFY Importado ENUM('VERDADERO', 'FALSO'),
MODIFY Origen VARCHAR(25) NOT NULL,
MODIFY Dia INT UNSIGNED NOT NULL,
MODIFY Mes INT UNSIGNED NOT NULL,
MODIFY Ano INT UNSIGNED NOT NULL;


SHOW TABLES;
DESCRIBE Nacimientos;
DESCRIBE Pedidos_Neptuno;
DESCRIBE Tablas_Extras;

SELECT * FROM clientes_neptuno;

SELECT * nombrecompania, ciudad, pais
FROM clientes_neptuno;

SELECT nombrecompania, ciudad pais
FROM clientes_neptuno
ORDER BY pais;

SELECT nombrecompania, ciudad, pais
FROM clientes_neptuno
ORDER BY pais
LIMIT 10;

SELECT nombrecompania, ciudad, pais
FROM clientes_neptuno
ORDER BY pais
LIMIT 5 OFFSET 10;

SELECT * FROM NACIMIENTOS WHERE NACIONALIDAD = 'Extranjera';

SELECT * FROM NACIMIENTOS WHERE EDAD_MADRE < 18 ORDER BY EDAD_MADRE;

SELECT * FROM NACIMIENTOS WHERE EDAD_MADRE = EDAD_PADRE;

SELECT EDAD_MADRE, EDAD_PADRE FROM NACIMIENTOS WHERE EDAD_MADRE <= EDAD_PADRE -40;

SELECT * FROM CLIENTES_NEPTUNO WHERE CLIENTES = 'Argentina';

SELECT * FROM CLIENTES_NEPTUNO WHERE PAIS != 'Argentina' ORDER BY PAIS;

SELECT * FROM NACIMIENTOS WHERE SEMANAS < 20 ORDER BY SEMANAS DESC;

SELECT * FROM NACIMIENTOS
WHERE SEXO = 'FEMENINO' AND NACIONALIDAD = 'EXTRANJERA' AND ESTADO_CIVIL_MADRE = 'SOLTERA' AND EDAD_MADRE > 40;


SELECT * FROM CLIENTES_NEPTUNO
WHERE PAIS IN ('ARGENTINA', 'BRASIL', 'VENEZUELA')
ORDER BY PAIS CIUDAD;

SELECT * FROM NACIMIENTOS
WHERE SEMANAS BETWEEN 20 AND 25
ORDERY BY SEMANAS;

SELECT * FROM NACIMIENTOS
WHERE COMUNA IN (1101, 3201, 5605, 8108, 9204, 13120, 15202)
ORDER BY COMUNA;

SELECT * FROM CLIENTES_NEPTUNO
WHERE Ciudad LIKE 'B____';

SELECT * FROM NACIMIENTOS WHERE HIJOS_TOTAL > 10;


